# Generated by Django 5.0.7 on 2024-07-29 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chai_images/')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'MASALA'), ('KL', 'KADAK'), ('SL', 'SULEMANI'), ('IL', 'ILACHI'), ('GL', 'GINGER')], max_length=2)),
            ],
        ),
    ]
