# Generated by Django 5.0.7 on 2024-07-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChaiVarity',
            new_name='ChaiVariety',
        ),
    ]
