# Generated by Django 5.0.7 on 2024-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m01', '0002_rename_chaivarity_chaivariety'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
